### ISSUE TITLE
Error when creating a SCSS file

### ISSUE THREAD

**Issue by mintcanary** [jenius/accord#108]
I'm trying Roots for the first time. I wanted to see if I could get SASS working, but after running `npm i scss --save` and then creating a `.scss. file I get the following:

```
Potentially unhandled rejection [21] TypeError: undefined is not a function
  at SCSS._render (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/scss.js:39:24)
  at SCSS.Adapter.render (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapter_base.js:122:19)
  at CompilePass.compile_or_pass (/usr/local/lib/node_modules/roots/lib/compiler.js:522:27)
  at tryCatchReject (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:845:30)
  at runContinuation1 (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:804:4)
  at Fulfilled.when (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:592:4)
  at Pending.run (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:483:13)
  at Scheduler._drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:62:19)
  at Scheduler.drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:27:9)
  at process._tickCallback (node.js:355:11)
```

**Comment by michaelkornblum** [comment]
Sam, what does your app.coffee file look like?

**Comment by Munter** [comment]
Sounds like a versioning conflict. The backwards compatible major version increases of sass have left wrapper tools like these in a bit of a mess. But I'm pretty sure the latest version of accord should have this covered. Looks like you are behind on accord

**Comment by mintcanary** [comment]
I have deleted the project now, but app.coffee would have been as default.

I installed Roots shortly before posting this issue, so presumably everything would be up to date?

**Comment by michaelkornblum** [comment]
Sam, in order to diagnose what's going on with your roots / sass setup, I
need to be able to see your project so I can replicate it on my own box. So
for now, here's what I need you to do.

1) Install roots version 3.1. Currently 3.2 is experiencing some issues,
but jenius and company are hammering away at it even as we speak.

2) Recreate your project, and either share it here, or push it up into a
git repository where I can make a pull request.

Additionally, what flavor of Sass are you using, libsass or ruby sass?

**Comment by mintcanary** [comment]
I can try using the older version. To clarify, you are suggesting 3.1.0 (not 3.2.1)?

To reiterate though, there won't be much to share. My project was the result of:
 1. Install Roots
 2. Create project using default template
 3. cd into project
 4 . run `npm i scss --save`
 5. save file with `.scss` extension
 6. edit and save scss file

**Comment by michaelkornblum** [comment]
Yes, Sam. Use Roots, 3.1.0. At present 3.2.0 is experiencing a bug that
pertains to image rendering. 3.1.0 is a more solid option. I'm going to try
to get libsass working on my setup, and informyou of how I got (or didn't
get it) to work. Stand by.

**Comment by michaelkornblum** [comment]
Sam, here are the steps you will need to take in order for roots to work
with sass.

** Install Roots 3.1 **
From the command line, enter:
```
$ npm install -g roots@3.1
```
npm will download and install roots 3.1.

** Instanciate Roots Site **
From the command-line, enter:
```
$ roots new <project name>
```
A new directory will be created that contains your new roots project. From
the terminal, change directories so your command line is inside the newly
created project.
```
$ cd <project name>

** Install requisite Node Modules **
The two modules that are needed are node-sass and accord. From the
command-line, enter:
```
$ npm install --save accord node-sass
```
Accord and node-sass will be installed within your roots project, and
referenced in your package.json file.

** Edit app.coffee file **
Use your favorite text editor to open the app.coffee file, located in your
roots project file. Make the edits below.

At the top of the app.coffee file, you will see a series of node module
requires. At the end of this section, add the following lines of code:
```
accord = require 'accord'
sass = accord.load 'node-sass'
```
On line 14, change the line that says ```css_pipeline(files:
'assets/css/*.styl')``` to ```css_pipeline(files: 'assets/css/*.scss)```

At the end of the file tab in once and add the final lines of code:
```
  sass:
    pretty: true
```
Save the file.

** Change .styl files with .scss files **
Delete all the files in the ```assets/css``` directory of your project.
Create a new file in ```assets/css``` named ```master.scss```. This file is
where you will start creating your sass files.

I hope you find this mini tutorial helpful. If you need additional help,
feel free to panic. Happy coding :)






On Wed, Sep 9, 2015 at 8:23 PM, Michael Kornblum <mkornblum71@gmail.com>
wrote:

> Yes, Sam. Use Roots, 3.1.0. At present 3.2.0 is experiencing a bug that
> pertains to image rendering. 3.1.0 is a more solid option. I'm going to try
> to get libsass working on my setup, and informyou of how I got (or didn't
> get it) to work. Stand by.
>
>
> On Wed, Sep 9, 2015 at 2:02 PM, Sam Smith <notifications@github.com>
> wrote:
>
>> I can try using the older version. To clarify, you are suggesting 3.1.0
>> (not 3.2.1)?
>>
>> To reiterate though, there won't be much to share. My project was the
>> result of:
>>
>>    1. Install Roots
>>    2. Create project using default template
>>    3. cd into project 4 . run npm i scss --save
>>    4. save file with .scss extension
>>    5. edit and save scss file
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jenius/accord/issues/108#issuecomment-139010454>.
>>
>
>

**Comment by michaelkornblum** [comment]
Sam, here are the steps you will need to take in order for roots to work with sass.

**Install Roots 3.1**
From the command line, enter:
```
$ npm install -g roots@3.1
```
npm will download and install roots 3.1.

**Instanciate Roots Site**
From the command-line, enter:
```
$ roots new <project name>
```
A new directory will be created that contains your new roots project. From the terminal, change directories so your command line is inside the newly created project.
```
$ cd <project name>
```
**Install requisite Node Modules**
The two modules that are needed are node-sass and accord. From the command-line, enter:
```
$ npm install --save accord node-sass 
```
Accord and node-sass will be installed within your roots project, and referenced in your package.json file.

**Edit app.coffee file**
Use your favorite text editor to open the app.coffee file, located in your roots project file. Make the edits below.

At the top of the app.coffee file, you will see a series of node module requires. At the end of this section, add the following lines of code:
```
accord = require 'accord'
sass = accord.load 'node-sass'
```
On line 14, change the line that says ```css_pipeline(files: 'assets/css/*.styl')``` to ```css_pipeline(files: 'assets/css/*.scss)```

At the end of the file tab in once and add the final lines of code:
```
  sass:
    pretty: true
```
Save the file.

**Change .styl files with .scss files**
Delete all the files in the ```assets/css``` directory of your project. Create a new file in ```assets/css``` named ```master.scss```. This file is where you will start creating your sass files.

I hope you find this mini tutorial helpful. If you need additional help, feel free to panic. Happy coding :)

**Comment by mintcanary** [comment]
Thanks @michaelkornblum that was indeed helpful, and I can confirm it works. I'm pretty sure I was missing one or two steps when I tried previously, so perhaps it would have worked with the latest version too.

I think you're missing a closing `'` in `css_pipeline..` by the way ;)

**Comment by michaelkornblum** [comment]
Actually, since Roots 3.1 is now the official latest version it will, in fact work :)

**Comment by mintcanary** [comment]
```coffee
sass
  pretty: true
```
Doesn't appear to do anything by the way. Without it, the CSS is still uncompressed. Setting it to `false` makes no difference either.

I also tried:
```coffee
sass:
    outputStyle: 'compressed'
```
but this too had no effect.

**Comment by jenius** [comment]
Oh, use `scss` instead of `sass`. Eventually this will change, but it's a massively breaking change so it has not dropped yet. It's a relic from the time when the engine could only do scss syntax, so it was a more appropriate name.

**Comment by mintcanary** [comment]
That seems to have no effect either @jenius but
```coffee
scss:
    outputStyle: 'compact'
```
and
```coffee
scss:
    outputStyle: 'compressed'
```
both work.

**Comment by jenius** [comment]
Ah yes, this would make sense, as `pretty` isn't an option for sass if I'm not mistaken. I was just using this because it was your example. It is an option for jade though!

Feel free to close this out if you feel like your issue has been resolved :grinning: 

Also I just want to say a huge sorry because I know better docs could have prevented you from even having this issue in the first place, but I just don't have time right now to make this happen. One day, I promise!

**Comment by mintcanary** [comment]
Yup, closing. Thanks guys. I look forward to seeing those docs ;)
