### ISSUE TITLE
Handlebars 4.0.2 is not currently supported.

### ISSUE THREAD

**Issue by ryanAbbott** [jenius/accord#109]
I posted an issue in jenius/roots and was asked to re-post here: 

Hello!
I tried creating a handlebars template (created an about.handlebars) and got the following error after `roots watch`:

[Error: handlebars version 4.0.2 is not currently supported]

I reinstalled handlbars version ~3 and it was error free.

**Comment by Munter** [comment]
Needs an adapter for the new major version. They are not hard to write. Copy/paste this and adapt to the new api: https://github.com/jenius/accord/blob/master/lib/adapters/handlebars/3.x.coffee

**Comment by jenius** [comment]
And if the major version bump didn't change the API at all, you can just change the filename to match the semver range. Basically accord just takes the filename and scans it as a semver matcher. It looks crazy, but it works.

For example, postcss recently bumped the major version but the API remained the same, and this is now how the filename looks: https://github.com/jenius/accord/tree/master/lib/adapters/postcss

**Comment by ryanAbbott** [comment]
Great, thank you both!

**Comment by jenius** [comment]
Fixed in the latest release. Upgrade away!

**Comment by ryanAbbott** [comment]
Thanks!
