### ISSUE TITLE
Error: babel version 4.4.3 is not currently supported

### ISSUE THREAD

**Issue by Munter** [jenius/accord#112]
I just got this error. The reason is obvious. But could the error message be improved to include the supported versions so the user will be able to conclude that things will work if they upgrade their engine, rather than conclude that accord just doesn't have babel support?

**Comment by jenius** [comment]
Yeah, that shouldn't be too tough to add. You'd just have to pull the adapter's filename and add it to the error message. Would you be interested in adding a PR for this? If not I can take care of it later.
