### ISSUE TITLE
Error: 'tried to require: node-sass'

### ISSUE THREAD

**Issue by tamtakoe** [jenius/accord#114]
Problem with node-sass install: https://github.com/sass/node-sass/issues/1189

Other plugins work correct

**Comment by jenius** [comment]
Did you install `node-sass`? Error seems clear to me. Accord doesn't auto install every compiler it supports, it's up to you to install them, it just provides a wrapper.

**Comment by tamtakoe** [comment]
Yes, I added all plugins to [package.json](https://github.com/tamtakoe/gulp-css-preprocessor/blob/master/package.json). This problem occurs not always associated with the npm. Somehow, npm could not connect the node-sass despite the fact that it is in the node_modules folder

**Comment by tamtakoe** [comment]
I'm think it's node-sass problem https://github.com/sass/node-sass/issues/1189#issuecomment-148693555

**Comment by jkarttunen** [comment]
I'm having similar problem with Stylus.
