### ISSUE TITLE
Stylus import issue on network paths

### ISSUE THREAD

**Issue by matthew-dean** [jenius/accord#115]
This could be a Stylus issue, but wanted to check here first since it's running through Accord.

At first I thought this was a Mac v. Windows issue, but then I realized the other variable in regards to Windows failing was that it was from a network path.

So, with this:
```
@import 'lib/kouto-swiss/'
```
On Windows, this fails with:
```
Cannot find module '\\psf\Home\git\kouto-swiss-master\node_modules\lib\kouto-swiss\package.json'
```
Windows compiling succeeds if the folder is copied locally.

**Comment by jenius** [comment]
I don't think this is an accord issue. Stylus imports are stylus' domain, we don't modify them. If you dig deeper and find that it is something on our end, definitely drop some more details here and we can re-open and take a closer look!

**Comment by jenius** [comment]
Also, you could always use axis, which works well and is better than kouto-swiss :wink:

**Comment by matthew-dean** [comment]
@jenius I don't use Stylus at all; this was just for my tests. Thanks for responding, I've filed it with Stylus as well (and it looks like it was a known, then presumed fixed, issue).
