### ISSUE TITLE
Adapter name not emitted on parseError in gulp-accord

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/accord#117]
Gulp only prints out the gulp plugin's name
![image](https://cloud.githubusercontent.com/assets/7485959/10758562/64a1a200-7cb2-11e5-9bc8-96daf59f48c3.png)

**Comment by jenius** [comment]
This is the wrong repo for the issue -- you are in accord, not gulp-accord. Also I don't understand what the issue is exactly. The error is quite clear, it's quite obviously a problem with stylus, and it tells you what the problem is and what line it is on. I don't see this really as a problem...

**Comment by jenius** [comment]
This is the wrong repo for the issue -- you are in accord, not gulp-accord. Also I don't understand what the issue is exactly. The error is quite clear, it's quite obviously a problem with stylus, and it tells you what the problem is and what line it is on. I don't see this really as a problem...

**Comment by jenius** [comment]
This is the wrong repo for the issue -- you are in accord, not gulp-accord. Also I don't understand what the issue is exactly. The error is quite clear, it's quite obviously a problem with stylus, and it tells you what the problem is and what line it is on. I don't see this really as a problem...

**Comment by FranzSkuffka** [comment]
Ok so I was around the gulp-accord repo and digging through the source calls for error throws but found nothing. This is probably handled by gulp anyways so there does not seem so much to be done.

I am currently implementing this for some folks that are not familiar with build systems yet and wanted to make the error messages as clear as possible. Do you think there is a way to print stylus above the pare error? I have some more plugins running through postcss afterwards which could be causing errors, too. Or does it make more sense to split up the tasks into stylus & postcss?

**Comment by jenius** [comment]
You would have to fork the repo and make this change yourself. It seems super clear to me that this is a stylus error. It shows where the error happened, in a stylus file, and even gives the filename. It says the word "stylus" in multiple places. If someone is looking at this error and unable to understand that it's a stylus error, or where to correct it, they are probably not a programmer and should not be attempting to debug errors anyway.

**Comment by FranzSkuffka** [comment]
welcome to my workplace. I am sorry for wasting your time on this one. just trying to do my best for the good of everyone.
