### ISSUE TITLE
Error: babel version 6.1.18 is not currently supported

### ISSUE THREAD

**Issue by Munter** [jenius/accord#121]
Related to Munter/tolk#46

**Comment by jenius** [comment]
Working on this. It's actually a somewhat involved fix unfortunately, as `babel` is now totally deprecated and you must use `babel-core`, so we have a major internal swap on our hands, and keeping full compatibility will be a challenge.

**Comment by Munter** [comment]
I appreciate the complexity of it. I just read through the babel 6 changelog and concluded I'm not going to be able to just do this in one sitting
