### ISSUE TITLE
Public API to add third-party adapters

### ISSUE THREAD

**Issue by davej** [jenius/accord#177]
It may be nice to have a public API to add third-party adapters, something like:

```js
accord.addAdapter('babel', require('some-third-party-babel-adapter'));
const babel = accord.load('babel');
// ...
```

By doing this, adapters could be maintained outside of accord, if you didn't feel they were a natural fit for the core library.

Any thoughts on this? I would be interested in PRing this myself (with a bit of guidance).

**Comment by jenius** [comment]
I'm ok with this!
