### ISSUE TITLE
support for custom adapters

### ISSUE THREAD

**Issue by jenius** [jenius/accord#6]
Sometimes you might want to build an adapter for a language that accord does not yet support, or something silly just for your purposes that accord does not plan on supporting. There should be a way to load a custom compiler into accord and use it, as long as you have written an adapter for it.

**Comment by mutza974** [comment]
@mutza974

**Comment by pccpolice** [comment]
[16NGNMJ.pdf](https://github.com/user-attachments/files/19265138/16NGNMJ.pdf)
