### ISSUE TITLE
Add jade2php adapter

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/accord#65]
The compiler interface should be similar, if not identical to jade's, so i would try this myself, but i have no idea how to set up an environmet to code and test accord adapters.
@jenius could you help me out right there? that would be killer.

https://www.npmjs.com/package/jade-php

**Comment by FranzSkuffka** [comment]
* User/Repository#Num: jlord/sheetsee.js#26

**Comment by FranzSkuffka** [comment]
I guess an approach  <a href="6#issuecomment-48647465"> this </a> as outlined by @slang800 would be the way to go.
correct me if I'm wrong.

**Comment by slang800** [comment]
Yeah, or you could just fork accord & implement it like any other adapter.

Also you might want to be careful with the way that jade-php mutates the jade instance. I've never used it before, but looking at the usage example, it seems like it duck-punches jade and _might_ screw with the global jade instance. Not totally sure, but it looks hacky.

**Comment by FranzSkuffka** [comment]
The Jade compiler inside roots still works even after running jade-php on loads of files.
As i mentioned, i have no idea how to setup a dev environement for creating and testing accord adapters

**Comment by slang800** [comment]
I mean when jade-php is being run within the same process as regular jade compilations.

It's pretty simple to setup a dev env:
 - make sure node.js / npm, and git are installed
 - fork & clone the accord repo into your machine
 - cd into the accord directory you just made
 - run `npm install` to get all the deps
 - start coding & use `npm test` to run the test cases

**Comment by FranzSkuffka** [comment]
Oh, of course. thanks alot. As I barely have used testing so far I am not aware of use cases like this.
I will file a pull request once I get something working.

**Comment by slang800** [comment]
Oh, our tests are mostly just comparing the result of compiling/rendering a bunch of files to known outputs. If you look around the tests directory you'll get the hang of it.

**Comment by jenius** [comment]
Hey @FranzSkuffka -- thanks for pitching in! If you have never worked with this kind of environment it definitely could be some time and effort before you get used to it. If you are working on some code for this and need help, feel free to open up a "Work in progress" pull request (just put `[WIP]` in the title), and we will review it.

You should definitely get familiar with testing practices before submitting anything, this is pretty important for projects like accord. Check out the [contributing file](https://github.com/jenius/accord/blob/master/contributing.md) for some help.

**Comment by FranzSkuffka** [comment]
@jenius i have checked out the contribution tips yesterday already and invested some time in copying the jade adapter tests etc. to test jade php. I think I'm somewhat down with the test workflow already as it makes perfect sense.
@slang800 i got what you meant with jade-php duck-punching the jade instance - seems like huge bogus to me. fortunately i have found the fully tested and more advanced alternative called <a href='https://github.com/SE7ENSKY/jade2php'> jade2php </a>. Strangely, it is not published on npm and the package.json is misconfigured as requiring it only works when specifying the full path.
I will try to fix it's package.json and in consequence creating a jade2php adapter instead.

**Comment by FranzSkuffka** [comment]
jade2php, tho, is not production-ready either and needs quite some work.

**Comment by jenius** [comment]
Ouch. Yeah this is something we sometimes discover in the process of trying to add adapters. This leads to either contributing back to the original library if we are particularly invested, or searching for a different solution, usually.

**Comment by FranzSkuffka** [comment]
Jade2php is ready for a production-ready release soon.

I am glad you were able to make dogescript work!

**Comment by jenius** [comment]
Ok cool! I guess we will wait until they are ready, then get merge in this pull request.

Oh yeah dogescript was the first priority. Much important. Very wow.

**Comment by FranzSkuffka** [comment]
I will send another pull request once i've written a proper adapter. i even missed the @compile call this time..
regarding the @compile private method: isn't it the same with most of the adapters? Why isn't it part of the adapter class as it does not access any local properties or functions?

**Comment by jenius** [comment]
Yeah, this is a good point. It's because it's the same in most adapters, but different in some. It just provides a way to catch any stray error that might be thrown from a compile method, really. Since it's different in a number of adapters, it is harder to pull out.

You don't have to use it by any means, it's just usually useful for catching errors. If the compiler throws errors in a different way, for example, you don't need it. But by passing invalid code, I was able to get most adapters to throw an error, which can only be caught and passed on using a try/catch. You can see error tests for a number of the adapters, try to generate an error for yours and make sure it's caught, then you are in the clear!

**Comment by FranzSkuffka** [comment]
Aye aye captain.
I think was about to write so many words, but, you know, YAGNI. lol. :smile:

**Comment by jenius** [comment]
Closing as we've given up on this one for now

**Comment by FranzSkuffka** [comment]
Hey there,
I'm currently implementing the adapter, forked from the jade adapter. It does compile as I saw when printing the <code>res</code> variable. But I am missing something here: The object that the compile function returns still contains the result, unlike that of the other adapters. When running the tests i get the following error:
<code>  3) jade2php should compile a string:
     Uncaught TypeError: Property 'result' of object #<Object> is not a function </code>

Source:
https://github.com/FranzSkuffka/accord/blob/master/lib/adapters/jade2php.coffee

Could you help me out on this one?

**Comment by jenius** [comment]
I'm sorry, I don't have the bandwidth at the moment to be able to help. Hopefully someone else will be able to!
