### ISSUE TITLE
Match extensions to compilers?

### ISSUE THREAD

**Issue by matthew-dean** [jenius/accord#69]
Say I have a list of files in a directory. Is there a way to ask accord which engines compile which file based on file extension? It seems like accord only works with a foreknowledge of exactly which compiler you want to use for one particular file, instead of choosing the engine based on the file (extension).

I poked around at the undocumented accord.all() function, and it looks like it's at least a way to return the LIST of supported compilers (which is essential), but it looks like you'd have to iterate through each one and load the adapter, before reading the "extensions" property. Is that correct? Or is there an easier way?

**Comment by slang800** [comment]
This is outside the scope of accord... What you want is [roots](http://roots.cx).

**Comment by matthew-dean** [comment]
Nah, roots isn't what I want. I'm just talking about file compilation. That's okay, I'll manually map extensions to lookup matching engines.

**Comment by jenius** [comment]
This is exactly what roots does though. It just compiles files, and it does this using the files' extensions. If you don't want the rest of roots' utilities, you can just check into the source and pull out the logic that does the file extension detection and matches it with accord compilers. If you are still interested, I link to the portion of the source that does this.

**Comment by matthew-dean** [comment]
Hmm, yeah roots has a ton of dependencies and most of it doesn't match my use case. I see https://github.com/jenius/roots/blob/master/lib/utils/adapter_finder.coffee which looks like what I described: iterating through a list of adapters (through adapter.all() or some other means), and loading each adapter to see what the extensions are, no? Or is it simpler than that?

**Comment by jenius** [comment]
Ah sorry, [v3](https://github.com/jenius/roots/tree/v3) is really the version you should be looking at, that's going to be released in the next week or so, the version on master is a bit outdated at the moment.

In the most recent version, it happens in two steps. In the first part, we scan the `package.json` and grab adapters from accord for any of the dependencies they have installed that have a matched adapter. This happens here:

https://github.com/jenius/roots/blob/v3/lib/config.coffee#L160-L186

This makes it almost magic for the user, they just `npm install jade`, for example, then any `.jade` file compiles correctly. It's pretty convenient. In the second piece, when the file is going through the compile pipeline, it matches the extension to it's adapter by running the file's extension against the accord adapters' `extensions` property to match them up.

https://github.com/jenius/roots/blob/v3/lib/compiler.coffee#L244-L267

Hope this helps!

**Comment by matthew-dean** [comment]
Awesome! It's still a little different from what I'm doing, but both of those are helpful and send me in the right direction. Cheers, and btw, Accord is a great project, and I hope you keep adding compilers! I was ecstatic when I came across it. Thanks! :)

**Comment by Munter** [comment]
Could this functionality maybe be extracted in to a micro module? I think I have a number of upcoming things that would benefit from this

**Comment by slang800** [comment]
You could also use [accord-cli](https://github.com/carrot/accord-cli) & pass the directory of files via the bash globstar

**Comment by jenius** [comment]
Thanks @matthew-dean! And yes @Munter I think that's a great idea. Could you detail a little more how you would expect the interface to work? Like a function that you could pass a file, and it would return the accord adapter for that file according to the extension?

**Comment by matthew-dean** [comment]
> Like a function that you could pass a file, and it would return the accord adapter for that file according to the extension?

Wait... isn't that what I said? o_O

**Comment by jenius** [comment]
Yeah, not something I would want to add to accord directly, but @Munter suggested a micro-package and I have no objections to that! Especially since there are now 2 people just in this thread that are interested.

**Comment by matthew-dean** [comment]
Ohh... I had no idea what a micro-package was, so I misunderstood.

**Comment by jenius** [comment]
Haha sorry it's just a very tiny npm package, I think

**Comment by matthew-dean** [comment]
By the way, this worked for me:

```js
	function getCompilers() {
		var accord = require('accord');
		var adapter;
		var extMap = {};
		_.each(accord.all(), function(obj, engine) {
			try {
				adapter = accord.load(engine);
				if(adapter) {
					_.each(adapter.extensions, function(val) {
						var prop = {
							engine: engine
							, output:  adapter.output
						};
						if(!extMap[val]) {
							extMap[val] = [ prop ];
						}
						else {
							extMap[val].push(prop);
						}
					});
				}
			}
			catch(e) {}
		});
		return extMap;
	}
```

**Comment by matthew-dean** [comment]
Of course... I'm assuming that an adapter will not load if the corresponding engine is not installed. Correct?

**Comment by jenius** [comment]
Yup, it will throw a clear error telling you to install the engine.

**Comment by matthew-dean** [comment]
Excellentsauce. Thanks! When I get a bit further in my project, I'd love to help you write a few more adapters.

**Comment by jenius** [comment]
Sounds great. Good luck with the project, and glad accord could be of help!
