### ISSUE TITLE
renderFile for scss adapter not resolving promise

### ISSUE THREAD

**Issue by Munter** [jenius/accord#86]
I'm running node-sass 2.0.1

When I used accord 0.15.2 `.scss`-files were compiled without a problem. With 0.16.0 my process hangs, seemingly with an unresolved promise.

I think I'll have time to dive into this later today and make a PR. Consider this a placeholder for now

**Comment by Munter** [comment]
This is a bit freakish. When I run up against a linked accord with the same git revision as release 0.16.0 it works. When I run with the npm installed version it doesn't.

This is my test script:

``` js
'use strict';
var accord = require('accord');

var scss = accord.load('scss');

scss.renderFile('fixtures/source/autoprefixer/unprefixed.scss').done(function (data) {
  console.log('success, scss', data);
}, function (data) {
  console.log('fail, scss', data);
});
```

I expected the promise to either resolve or fail, but neither happens

**Comment by Munter** [comment]
Ok. One step closer. Apparently I have 3 different versions of node-sass in play.

global: 0.9.5-rc1
accord: 3.0.0-pre
fusile: 2.0.1

So when I'm running the release version of accord 0.16.0 I am running against fusiles node-sass@2.0.1, while the linked debug version runs accords locally installed node-sass@3.0.0-pre.

Accord seems to be incompatible with anything below node-sass v3.x, which seems to be a bit optimistic. I'll make a pull request with backwards compatibility

**Comment by jenius** [comment]
Yup, sorry I am updating adapters just for the latest versions each release. Happy to accept backwards compatibility though!

**Comment by jenius** [comment]
This will be fixed by evergreen support for adapters, coming soon
